using System;

public class PasswordGenerator
{
  public static void Main (string[] args)
  {
    int letters = 0;
    int numbers = 0;
    int specialcharacters =0;
    
    string Letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    string Numbers = "1234567890";
    string SpecialCharacters = "@#$_&-+()/*':;!?";
    
    Console.WriteLine("=== Password Generator ===");
    Console.WriteLine();
    Console.WriteLine("Welcome to the Password Generator! To create a password generated by this script, please answer some questions.");
    Console.WriteLine();
    Console.WriteLine("First, do you prefer to have letters in your password? (y/n)");
    
    while (true)
    {
      string answer1 = Console.ReadLine().ToLower();
      
      switch (answer1)
      {
        case "y":
        case "yes":
        
        letters = 1;
        Console.WriteLine();
        Console.WriteLine("Letters activated!");
        break;
        
        case "n":
        case "no":
        
        letters = 0;
        Console.WriteLine();
        Console.WriteLine("Letters not activated!");
        break;
        
        default:
        
        Console.WriteLine();
        Console.WriteLine("Sorry, but I can't understand your answer");
        continue;
      }    
      break;
    }
    
    Console.WriteLine();
    Console.WriteLine("Great, now, do you prefer to have numbers in your password?");
    
    while (true)
    {
      string answer2 = Console.ReadLine().ToLower();
      
      switch (answer2)
      {
        case "y":
        case "yes":
        
        numbers = 1;
        Console.WriteLine();
        Console.WriteLine("Numbers activated!");
        break;
        
        case "n":
        case "no":
        
        numbers = 0;
        Console.WriteLine();
        Console.WriteLine("Numbers not activated!");
        break;
        
        default:
        
        Console.WriteLine();
        Console.WriteLine("Sorry, but I can't understand your answer...");
        continue;
      }
      break;
    }
    
    Console.WriteLine();
    Console.WriteLine("Last answer, do you prefer to have special characters in your password?");
    
    while (true)
    {
      string answer3 = Console.ReadLine().ToLower();
      
      switch (answer3)
      {
        case "y":
        case "yes":
        
        specialcharacters = 1;
        Console.WriteLine();
        Console.WriteLine("Special Characters activated!");
        break;
        
        case "n":
        case "no":
        
        specialcharacters = 0;
        Console.WriteLine();
        Console.WriteLine("Special Characters not activated!");
        break;
        
        default:
        
        Console.WriteLine();
        Console.WriteLine("Sorry, but I can't understand your answer...");
        continue;
      }
      break;
    }
    
    if (letters == 0 && numbers == 0 && specialcharacters == 0)
    {
      Console.WriteLine();
      Console.WriteLine("Bro, really? You gonna create a Password with nothing? NOTHING??? Well,  good luck genius, getting hacked for a 'invisible' password!");
      Environment.Exit(0);
    }
    
    string characters = "";
    
    if (letters == 1)
    {
      characters += Letters;
    }
   
    if (numbers == 1)
    {
      characters += Numbers;
    }
    
    if (specialcharacters == 1)
    {
      characters += SpecialCharacters;
    }
    
    Console.WriteLine();
    Console.WriteLine("Now, how many characters do you want in your password?");
    int length = Convert.ToInt32(Console.ReadLine());
    
    string Password = "";
    Random rnd = new Random();
    
    for (int i = 0; i < length; i++)
    {
      int index = rnd.Next(0, characters.Length);
      Password += characters[index];
    }
    
    Console.WriteLine($"The password generated is: {Password}");
  }
}